name: Dash Coupon Generator BE Deployment Automizer

on:
  push:
    branches:
      - "main"

jobs:
  coupon-generate-server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Image Build & Push [COUPON_GENERATOR]
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: dashajou/dash-be:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max